### ISSUE TITLE
Unable to clear DB when primary key field has the different name from id

### ISSUE THREAD

**Issue by Goodmain** [RonasIT/laravel-helpers#95]
For example, you have PostgreSQL DB with a table `records` where the primary key is `order_hash`. In this case, when you try to test this table you will got en error related to the sequence.

Here the place where an error throws:
https://github.com/RonasIT/laravel-helpers/blob/master/src/Traits/FixturesTrait.php#L167

```bash
Illuminate\Database\QueryException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "order_hash" does not exist
LINE 1: ...CT setval('records_id_seq', (select max(id) from r...
                                                             ^ (Connection: pgsql, SQL: SELECT setval('records_id_seq', (select max(id) from records));
...
```

As a possible solution... Maybe instead of getting tables and iteration them we should get all sequences and work with this data?

```sql
SELECT sequence_schema, sequence_name 
FROM information_schema.sequences 
ORDER BY sequence_name;
```

Or we could get sequesnces with the related tables

```sql
SELECT * FROM information_schema.columns WHERE column_default LIKE 'nextval%';
```

**Comment by DenTray** [comment]
@Goodmain sequences should be reset only for tables that had been cleared in `setUp` method.

I believe that the best way will be to keep current logic of sequences resetting, but generate the sequence name by using a key field instead of hard-coded `id`.

Another way - will get sequences filtered by table name if we have such ability. Please advise.

**Comment by Goodmain** [comment]
Fix pushed to the master branch

**Comment by DenTray** [comment]
@Goodmain thanks! It works as expected now
